spring:
  application:
    name: spock-example

  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        timezone.default_storage: NORMALIZE_UTC
        jdbc.time_zone: UTC

mysql:
  driver-class-name: com.mysql.cj.jdbc.Driver
  jdbc-url: jdbc:mysql://localhost:3306/loopers
  username: application
  password: application
  pool-name: spock-example-pool
  maximum-pool-size: 40
  minimum-idle: 30
  connection-timeout: 3000
  validation-timeout: 5000
  keepalive-time: 0
  max-lifetime: 1800000
  leak-detection-threshold: 0
  initialization-fail-timeout: 1
  data-source-properties:
    rewriteBatchedStatements: true

---

spring.config.activate.on-profile: test

datasource:
  mysql:
    maximum-pool-size: 10
    minimum-idle: 5
